namespace JianpuEditor.Controls
{
    /// <summary>Every icon the ribbon toolbar can draw. See <see cref="RibbonIconRenderer"/>.</summary>
    public enum RibbonIcon
    {
        None,
        Play,
        Stop,
        Instrument,
        MeasureAdd,
        OctaveUp,
        OctaveDown,
        TransposeUp,
        TransposeDown,
        Split,
        Merge,
        Dotted,
        Extend,
        Shorten,
        Tie,
        Grace,
        Trill,
        Turn,
        Mordent,
        Fermata,
        BreathMark,
        Staccato,
        Accent,
        Tenuto,
        Duplicate,
        Delete,
        Library,
        Key,
        Tempo,
        Measures,
        Engine,
        ZoomIn,
        ZoomOut
    }
}
